version: '3.8'

services:
  web:
    image: nginx_custom:latest
    ports:
      - "8094:80"
    deploy:
      mode: replicated
      replicas: 1
    configs:
      - source: my_index_html
        target: /usr/share/nginx/html/index.html
    networks:
      - my_network

configs:
  my_index_html:
    file: ./index.html

networks:
  my_network:
    driver: overlay
